{
 "title": "AMQ Streams Dashboard",
 "tags": [
  "kafka ",
  "jmx exporter",
  "Kafka Broker",
  "Kafka Connect",
  "Zookeeper"
 ],
 "time": { "from": "2020-08-24T17:02:07.281Z", "to": "2020-08-24T17:12:07.281Z" },
 "panels": [
  { "title": "Merge ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Replication In (bytes/s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_replicationbytesin_total{job=~\"kafka-jmx-exporter\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replication In (bytes/s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_replicationbytesout_total{job=~\"kafka-jmx-exporter\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Packets Received / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "pps", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "rate (zookeeper_packetsreceived{job=~\"zookeeper-jmx-exporter\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Packets Sent / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "pps", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "rate (zookeeper_packetssent{job=~\"zookeeper-jmx-exporter\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes requested / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_network_requestmetrics_requestbytes_count{job=~\"kafka-jmx-exporter\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "insyncreplicascount",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min (sum (kafka_cluster_partition_insyncreplicascount{topic!~\"^_.*\",job=~\"kafka-jmx-exporter\"}) by (topic,partition)) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "kafka_cluster_partition_underminisr",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (kafka_cluster_partition_underminisr{job=~\"kafka-jmx-exporter\",topic=~\"^[^_].*\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Latencia zookeeper (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_zookeeperclientmetrics_zookeeperrequestlatencyms{quantile=\"0.99\",job=~\"kafka-jmx-exporter\"}",
     "legendFormat": "{{instance}} 99%"
    },
    {
     "expr": "kafka_server_zookeeperclientmetrics_zookeeperrequestlatencyms{quantile=\"0.95\",job=~\"kafka-jmx-exporter\"}",
     "legendFormat": "{{instance}} 95%"
    }
   ]
  },
  {
   "title": "kafka_controller_controllerstats_isrchangerateandtimems",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate (kafka_controller_controllerstats_isrchangerateandtimems_count{job=~\"kafka-jmx-exporter\"}[30s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Kafka Streams", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Kafka Streams Status",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=\"kafka-streams-jmx-exporter\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Created Total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_streams_task_created_total"
    }
   ]
  },
  {
   "title": "Poll Latency Max (ms)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kafka_streams_poll_latency_max" }
   ]
  },
  {
   "title": "Commit Latency Avg",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 30 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_commit_latency_avg",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Process Rate ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_process_latency_avg",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Commit Total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kafka_streams_commit_total" }
   ]
  },
  {
   "title": "Poll Total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kafka_streams_poll_total" }
   ]
  },
  {
   "title": "Process Total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kafka_streams_process_total" }
   ]
  },
  {
   "title": "Process Latency Avg",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 37 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_process_latency_avg",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Poll Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 37 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "kafka_streams_poll_rate", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "Producers e Consumers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Consumer Connections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (rate(kafka_consumer_connection_count{job=\"kafka-consumer-jmx-exporter\"}[1m]))"
    }
   ]
  },
  {
   "title": "Producer Connections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (rate(kafka_producer_connection_count{job=\"kafka-producer-jmx-exporter\"}[1m]))"
    }
   ]
  },
  {
   "title": "Consumer Producer Status",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=\"kafka-consumer-jmx-exporter\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Consumer Producer Status",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=\"kafka-producer-jmx-exporter\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Producers vs Consumers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short", "label": "Conn" }
   ],
   "targets": [
    {
     "expr": "count (rate(kafka_consumer_connection_count{job=\"kafka-consumer-jmx-exporter\"}[1m]))",
     "legendFormat": "Consumers"
    },
    {
     "expr": "count (rate(kafka_producer_connection_count{job=\"kafka-producer-jmx-exporter\"}[1m]))\n",
     "legendFormat": "Producers"
    }
   ]
  },
  {
   "title": "Producer Outgoing bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_producer_outgoing_byte_total{job=\"kafka-producer-jmx-exporter\"})",
     "legendFormat": "{{clientId}}"
    }
   ]
  },
  {
   "title": "Consumer Outgoing bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 52 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumer_outgoing_byte_total{job=\"kafka-consumer-jmx-exporter\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Producer Incoming bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_producer_incoming_byte_total{job=\"kafka-producer-jmx-exporter\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Consumer Incoming bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 52 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumer_incoming_byte_total{job=\"kafka-consumer-jmx-exporter\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Kafka Geral", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Number of Brokers Online",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_server_replicamanager_leadercount{job=\"kafka-jmx-exporter\"} > 0) by (job)"
    }
   ]
  },
  {
   "title": "Active Controllers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount{job=\"kafka-jmx-exporter\"}) by (job)"
    }
   ]
  },
  {
   "title": "Unclean Leader Election Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_controllerstats_uncleanleaderelections_total{job=\"kafka-jmx-exporter\"}) by (job)"
    }
   ]
  },
  {
   "title": "Kafka Status",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 7, "x": 9, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=\"kafka-jmx-exporter\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 60 },
   "yaxes": [
    { "format": "percent", "label": "% time in GC" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"kafka-jmx-exporter\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Online Partitions",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 65 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_partitioncount)"
    }
   ]
  },
  {
   "title": "Under-replicated Partitions",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 65 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions)"
    }
   ]
  },
  {
   "title": "Offline Partitions",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 65 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount)"
    }
   ]
  },
  {
   "title": "Bytes Out Per Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 65 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesout_total{job=\"kafka-jmx-exporter\",topic!=\"\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages Per Topic - In x Out",
   "type": "graph",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short", "label": "Out   /    In" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_messagesin_total{job=\"kafka-jmx-exporter\",topic!=\"\"}[5m]))  ",
     "legendFormat": "in"
    },
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_totalproducerequests_total{job=\"kafka-jmx-exporter\",topic!=\"\"}[5m]))  ",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 70 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kafka-jmx-exporter\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 75 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{job=\"kafka-jmx-exporter\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Topic Leaders per Broker",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(kafka_server_replicamanager_leadercount{job=\"kafka-jmx-exporter\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Bytes In/Out Per Second",
   "type": "graph",
   "gridPos": { "h": 13, "w": 16, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes(-) / Bytes (+)" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesin_total{job=\"kafka-jmx-exporter\",topic!=\"\"}[5m]))",
     "legendFormat": "in: {{ topic }}"
    },
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesout_total{job=\"kafka-jmx-exporter\",topic!=\"\"}[5m]))",
     "legendFormat": "out:  {{ topic }}"
    }
   ]
  },
  {
   "title": "Replica per Topic Partition",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_in_sync_replica{topic!=\"__consumer_offsets\"}) by (topic)",
     "legendFormat": "{{ topic }}"
    }
   ]
  },
  { "title": "Zookeeper", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "Quorum size",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(zookeeper_quorumsize)" }
   ]
  },
  {
   "title": "Alive Connections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(zookeeper_numaliveconnections)"
    }
   ]
  },
  {
   "title": "Request Latency - Max x Min x Avg ",
   "type": "graph",
   "description": "Amount of time it takes for the server to respond to a client request (since the server was started).",
   "gridPos": { "h": 18, "w": 16, "x": 8, "y": 96 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(zookeeper_maxrequestlatency[5m])",
     "legendFormat": "Max - {{ instance }}"
    },
    {
     "expr": "rate(zookeeper_minrequestlatency[5m])",
     "legendFormat": "Min -  {{ instance }}"
    },
    {
     "expr": "rate(zookeeper_avgrequestlatency[5m])",
     "legendFormat": "Avg - {{ instance }}"
    }
   ]
  },
  {
   "title": "Watchers",
   "type": "stat",
   "description": "Number of watchers over Zookeeper znodes.\t",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(zookeeper_inmemorydatatree_watchcount)"
    }
   ]
  },
  {
   "title": "Znodes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(zookeeper_inmemorydatatree_nodecount)"
    }
   ]
  },
  {
   "title": "Zookeeper Status",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 110 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=\"zookeeper-jmx-exporter\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 114 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"zookeeper-jmx-exporter\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Queued requests",
   "type": "graph",
   "description": "Number of queued requests in the server. This goes up when the server receives more requests than it can process.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 114 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "zookeeper_outstandingrequests", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 123 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{job=\"zookeeper-jmx-exporter\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 123 },
   "yaxes": [
    { "format": "percent", "label": "% time in GC" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"zookeeper-jmx-exporter\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Kafka Connect", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 132 } },
  {
   "title": "Number of Connectors",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 133 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kafka_connect_worker_connector_startup_success_total"
    }
   ]
  },
  {
   "title": "Kafka Connect Status",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 7, "x": 3, "y": 133 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=\"kafka-connect-jmx-exporter\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 133 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kafka-connect-jmx-exporter\"}[1m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Producer Connections",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 139 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count (rate(kafka_producer_connection_count{job=\"kafka-connect-jmx-exporter\"}[1m]))"
    }
   ]
  },
  {
   "title": "Connector task state",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 3, "y": 139 },
   "yaxes": [
    { "format": "short", "label": "Conn" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_running_task_count{job=~\"kafka-connect-jmx-exporter\"})",
     "legendFormat": "running"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_paused_task_count{job=~\"kafka-connect-jmx-exporter\"})",
     "legendFormat": "paused"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_failed_task_count{job=~\"kafka-connect-jmx-exporter\"})",
     "legendFormat": "failed"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_destroyed_task_count{job=~\"kafka-connect-jmx-exporter\"})",
     "legendFormat": "destroyed"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_unassigned_task_count{job=~\"kafka-connect-jmx-exporter\"})",
     "legendFormat": "unassigned"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 141 },
   "yaxes": [
    { "format": "percent", "label": "% time in GC" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"kafka-connect-jmx-exporter\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 141 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{job=\"kafka-connect-jmx-exporter\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Consumer Connections",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 144 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count (rate(kafka_consumer_connection_count{job=\"kafka-connect-jmx-exporter\"}[1m]))"
    }
   ]
  },
  {
   "title": "Producers vs Consumers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 3, "y": 147 },
   "yaxes": [
    { "format": "short", "label": "Conn" }
   ],
   "targets": [
    {
     "expr": "count (rate(kafka_consumer_connection_count{job=\"kafka-connect-jmx-exporter\"}[1m]))",
     "legendFormat": "Consumers"
    },
    {
     "expr": "count (rate(kafka_producer_connection_count{job=\"kafka-connect-jmx-exporter\"}[1m]))\n",
     "legendFormat": "Producers"
    }
   ]
  },
  {
   "title": "Incoming bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 148 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumer_incoming_byte_total{job=\"kafka-connect-jmx-exporter\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Outgoing bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 148 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumer_outgoing_byte_total{job=\"kafka-connect-jmx-exporter\"})",
     "legendFormat": "{{clientId}}"
    }
   ]
  },
  {
   "title": "Number of Tasks",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 149 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kafka_connect_worker_task_count"
    }
   ]
  }
 ]
}