{
 "title": "AMQ Streams Dashboard",
 "tags": [
  "kafka ",
  "jmx exporter",
  "Kafka Broker",
  "Kafka Connect",
  "Zookeeper"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Diff", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Alive connections",
   "type": "bargauge",
   "description": "Number of clients connected to ZooKeeper",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "zookeeper_numaliveconnections{job=~\"zookeeper-jmx-exporter\"}",
     "legendFormat": "{{instance}}: {{replicaId}} [{{memberType}}]"
    }
   ]
  },
  {
   "title": "Packets Received / sec",
   "type": "graph",
   "description": "The number of packets received.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "pps", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "rate (zookeeper_packetsreceived{job=~\"zookeeper-jmx-exporter\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replication In (bytes/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_replicationbytesout_total{job=~\"kafka-jmx-exporter\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Processos Java",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "jvm_info{job=~\"kafka-jmx-exporter\"}"
    }
   ]
  },
  {
   "title": "Bytes requested / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_network_requestmetrics_requestbytes_count{job=~\"kafka-jmx-exporter\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Zookeeper disconnects / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_sessionexpirelistener_zookeeperdisconnects_total{job=~\"kafka-jmx-exporter\"}[30s])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "insyncreplicascount",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min (sum (kafka_cluster_partition_insyncreplicascount{topic!~\"^_.*\",job=~\"kafka-jmx-exporter\"}) by (topic,partition)) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Packets Sent / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "pps", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "rate (zookeeper_packetssent{job=~\"zookeeper-jmx-exporter\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replication In (bytes/s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 23 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_replicationbytesin_total{job=~\"kafka-jmx-exporter\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "kafka_cluster_partition_underminisr",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (kafka_cluster_partition_underminisr{job=~\"kafka-jmx-exporter\",topic=~\"^[^_].*\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "kafka_controller_controllerstats_isrchangerateandtimems",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate (kafka_controller_controllerstats_isrchangerateandtimems_count{job=~\"kafka-jmx-exporter\"}[30s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Latencia zookeeper (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_zookeeperclientmetrics_zookeeperrequestlatencyms{quantile=\"0.99\",job=~\"kafka-jmx-exporter\"}",
     "legendFormat": "{{instance}} 99%"
    },
    {
     "expr": "kafka_server_zookeeperclientmetrics_zookeeperrequestlatencyms{quantile=\"0.95\",job=~\"kafka-jmx-exporter\"}",
     "legendFormat": "{{instance}} 95%"
    }
   ]
  },
  {
   "title": "Delayed Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_delayedoperationpurgatory_numdelayedoperations{job=~\"kafka-jmx-exporter\",delayedOperation=\"Fetch\"}",
     "legendFormat": "{{delayedOperation}}:{{instance}}"
    },
    {
     "expr": "kafka_server_delayedoperationpurgatory_numdelayedoperations{job=~\"kafka-jmx-exporter\",delayedOperation=\"Produce\"}",
     "legendFormat": "{{delayedOperation}}:{{instance}}"
    }
   ]
  },
  {
   "title": "Reducao de InSyncReplica",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_replicamanager_isrshrinks_total{job=~\"kafka-jmx-exporter\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Kafka Streams",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kafka Streams Status",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "up{job=\"kafka-streams-jmx-exporter\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Created Total",
     "type": "stat",
     "description": "The total number of tasks created.",
     "gridPos": { "h": 7, "w": 3, "x": 3, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_streams_task_created_total"
      }
     ]
    },
    {
     "title": "Poll Latency Max (ms)",
     "type": "stat",
     "description": "The maximum execution time in ms for polling across all running tasks of this thread.",
     "gridPos": { "h": 7, "w": 3, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "kafka_streams_poll_latency_max" }
     ]
    },
    {
     "title": "Commit Latency Avg",
     "type": "graph",
     "description": "The average execution time in ms for committing, across all running tasks of this thread.",
     "gridPos": { "h": 7, "w": 8, "x": 9, "y": 2 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_commit_latency_avg",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Poll Rate",
     "type": "graph",
     "description": "The average number of polls per second.",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      { "expr": "kafka_streams_poll_rate", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Commit Total",
     "type": "stat",
     "description": "The total number of commit calls across all tasks.",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "kafka_streams_commit_total" }
     ]
    },
    {
     "title": "Poll Total",
     "type": "stat",
     "description": "The total number of poll calls across all tasks.",
     "gridPos": { "h": 7, "w": 3, "x": 3, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "kafka_streams_poll_total" }
     ]
    },
    {
     "title": "Process Total",
     "type": "stat",
     "description": "The total number of process calls across all tasks.",
     "gridPos": { "h": 7, "w": 3, "x": 6, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "kafka_streams_process_total" }
     ]
    },
    {
     "title": "Process Latency Avg",
     "type": "graph",
     "description": "The average execution time in ms for processing, across all running tasks of this thread.",
     "gridPos": { "h": 7, "w": 8, "x": 9, "y": 9 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_process_latency_avg",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Process Rate ",
     "type": "graph",
     "description": "The average number of process calls per second.",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 9 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      { "expr": "kafka_streams_process_rate", "legendFormat": "{{instance}}" }
     ]
    }
   ]
  },
  { "title": "Producers e Consumers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Consumer Connections",
   "type": "stat",
   "description": "The current number of active connections (Consumers only)",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (rate(kafka_consumer_connection_count{job=\"kafka-consumer-jmx-exporter\"}[1m]))"
    }
   ]
  },
  {
   "title": "Producer Connections",
   "type": "stat",
   "description": "The current number of active connections (Producer only)",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (rate(kafka_producer_connection_count{job=\"kafka-producer-jmx-exporter\"}[1m]))"
    }
   ]
  },
  {
   "title": "Consumer Producer Status",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=\"kafka-consumer-jmx-exporter\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Consumer Producer Status",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=\"kafka-producer-jmx-exporter\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Producer Incoming bytes",
   "type": "graph",
   "description": "The average number of responses received per second for a node.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_producer_incoming_byte_total{job=\"kafka-producer-jmx-exporter\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Producer Outgoing bytes",
   "type": "graph",
   "description": "The average number of outgoing bytes sent per second for a node.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 47 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_producer_outgoing_byte_total{job=\"kafka-producer-jmx-exporter\"})",
     "legendFormat": "{{clientId}}"
    }
   ]
  },
  {
   "title": "Producers vs Consumers",
   "type": "graph",
   "description": "The current number of active connections.\n1-Consumers\n2-Producers",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short", "label": "Conn" }
   ],
   "targets": [
    {
     "expr": "count (rate(kafka_consumer_connection_count{job=\"kafka-consumer-jmx-exporter\"}[1m]))",
     "legendFormat": "Consumers"
    },
    {
     "expr": "count (rate(kafka_producer_connection_count{job=\"kafka-producer-jmx-exporter\"}[1m]))\n",
     "legendFormat": "Producers"
    }
   ]
  },
  {
   "title": "Consumer Incoming bytes",
   "type": "graph",
   "description": "The average number of responses received per second for a node.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumer_incoming_byte_total{job=\"kafka-consumer-jmx-exporter\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Consumer Outgoing bytes",
   "type": "graph",
   "description": "The average number of outgoing bytes sent per second for a node.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 54 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumer_outgoing_byte_total{job=\"kafka-consumer-jmx-exporter\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Kafka Geral",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Brokers Online",
     "type": "stat",
     "description": "Number of online brokers on the cluster. The metric is based on the number of leaders on tthe broker",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kafka_server_replicamanager_leadercount{job=\"kafka-jmx-exporter\"} > 0) by (job)"
      }
     ]
    },
    {
     "title": "Active Controllers",
     "type": "stat",
     "description": "Number of active controllers in the cluster. Alert if value is anything other than 1.",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount{job=\"kafka-jmx-exporter\"}) by (job)"
      }
     ]
    },
    {
     "title": "Unclean Leader Election Rate",
     "type": "stat",
     "description": "  Unclean leader election rate.\nUnclean leader elections occur when there is no qualified partition leader among Kafka brokers",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kafka_controller_controllerstats_uncleanleaderelections_total{job=\"kafka-jmx-exporter\"}) by (job)"
      }
     ]
    },
    {
     "title": "Kafka Status",
     "type": "bargauge",
     "description": "Brokers UP",
     "gridPos": { "h": 10, "w": 7, "x": 9, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "up{job=\"kafka-jmx-exporter\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Time spent in GC",
     "type": "graph",
     "description": "GCs per second over the last 5 minutes,",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 4 },
     "yaxes": [
      { "format": "percent", "label": "% time in GC" }
     ],
     "targets": [
      {
       "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"kafka-jmx-exporter\"}[5m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Online Partitions",
     "type": "singlestat",
     "description": "The number of partitions under the minimum In-Sync Replica (ISR) count. The ISR count indicates the set of replicas that are up-to-date with the leader.",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 9 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kafka_server_replicamanager_partitioncount)"
      }
     ]
    },
    {
     "title": "Under-replicated Partitions",
     "type": "singlestat",
     "description": "The number of partitions that have not been fully replicated in the follower replicas.",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 9 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions)"
      }
     ]
    },
    {
     "title": "Offline Partitions",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 9 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount)"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "short", "label": "Cores" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=\"kafka-jmx-exporter\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Messages Per Topic - In x Out",
     "type": "graph",
     "description": "1-The rate at which individual messages are consumed by the broker.\n2--The rate at which individual messages are produced by the broker. ",
     "gridPos": { "h": 12, "w": 16, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short", "label": "Out   /    In" }
     ],
     "targets": [
      {
       "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_messagesin_total{job=\"kafka-jmx-exporter\",topic!=\"\"}[5m]))  ",
       "legendFormat": "in"
      },
      {
       "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_totalproducerequests_total{job=\"kafka-jmx-exporter\",topic!=\"\"}[5m]))  ",
       "legendFormat": "out"
      }
     ]
    },
    {
     "title": "JVM Memory",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 14 },
     "yaxes": [
      { "format": "bytes", "label": "Memory" }
     ],
     "targets": [
      {
       "expr": "sum without(area)(jvm_memory_bytes_used{job=\"kafka-jmx-exporter\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Bytes Out Per Second",
     "type": "graph",
     "description": "The rate at which data is fetched and read from the broker by consumers.",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 19 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesout_total{job=\"kafka-jmx-exporter\",topic!=\"\"}[5m]))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Topic Leaders per Broker",
     "type": "graph",
     "description": "The number of replicas for which this broker is the leader",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(kafka_server_replicamanager_leadercount{job=\"kafka-jmx-exporter\"})",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Bytes In/Out Per Second",
     "type": "graph",
     "description": "1-The rate at which data sent from producers is consumed by the broke\n2-The rate at which data is fetched and read from the broker by consumers.",
     "gridPos": { "h": 13, "w": 16, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes(-) / Bytes (+)" }
     ],
     "targets": [
      {
       "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesin_total{job=\"kafka-jmx-exporter\",topic!=\"\"}[5m]))",
       "legendFormat": "in: {{ topic }}"
      },
      {
       "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesout_total{job=\"kafka-jmx-exporter\",topic!=\"\"}[5m]))",
       "legendFormat": "out:  {{ topic }}"
      }
     ]
    },
    {
     "title": "Replica per Topic Partition",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_topic_partition_in_sync_replica{topic!=\"__consumer_offsets\"}) by (topic)",
       "legendFormat": "{{ topic }}"
      }
     ]
    },
    {
     "title": "Replication In (bytes/s)",
     "type": "graph",
     "description": "The rate at which data is sent from the broker to other brokers. This metric is useful to monitor if the broker is a leader for a group of partitions.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "rate(kafka_server_brokertopicmetrics_replicationbytesout_total{job=~\"kafka-jmx-exporter\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Bytes requested / sec",
     "type": "graph",
     "description": "The size of requests, in bytes, made for the request type identified by the request property of the MBean name. Separate MBeans for all available request types are listed under the RequestBytes node.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "rate(kafka_network_requestmetrics_requestbytes_count{job=~\"kafka-jmx-exporter\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "kafka_cluster_partition_underminisr",
     "type": "graph",
     "description": "The number of partitions under the minimum In-Sync Replica (ISR) count. The ISR count indicates the set of replicas that are up-to-date with the leader.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (kafka_cluster_partition_underminisr{job=~\"kafka-jmx-exporter\",topic=~\"^[^_].*\"}) by (topic)",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Processos Java",
     "type": "table-old",
     "description": "Provides information on a Java Virtual Machine installed on the server that executes the jmx-exporter",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "targets": [
      {
       "expr": "jvm_info{job=~\"kafka-jmx-exporter\"}"
      }
     ]
    },
    {
     "title": "Reducao de InSyncReplica",
     "type": "graph",
     "description": "The rate at which the number of ISRs in the broker decreases",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_server_replicamanager_isrshrinks_total{job=~\"kafka-jmx-exporter\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "insyncreplicascount",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "min (sum (kafka_cluster_partition_insyncreplicascount{topic!~\"^_.*\",job=~\"kafka-jmx-exporter\"}) by (topic,partition)) by (topic)",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "kafka_controller_controllerstats_isrchangerateandtimems",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate (kafka_controller_controllerstats_isrchangerateandtimems_count{job=~\"kafka-jmx-exporter\"}[30s])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Replication In (bytes/s)",
     "type": "graph",
     "description": "The rate at which data sent from other brokers is consumed by the follower broker.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "rate(kafka_server_brokertopicmetrics_replicationbytesin_total{job=~\"kafka-jmx-exporter\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Zookeeper disconnects / sec",
     "type": "graph",
     "description": "The status of the broker’s connection to Zookeeper.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(kafka_server_sessionexpirelistener_zookeeperdisconnects_total{job=~\"kafka-jmx-exporter\"}[30s])",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Delayed Operations",
     "type": "graph",
     "description": "1-The number of fetch requests in the fetch purgatory\n2-The number of send requests in the producer purgatory.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_server_delayedoperationpurgatory_numdelayedoperations{job=~\"kafka-jmx-exporter\",delayedOperation=\"Fetch\"}",
       "legendFormat": "{{delayedOperation}}:{{instance}}"
      },
      {
       "expr": "kafka_server_delayedoperationpurgatory_numdelayedoperations{job=~\"kafka-jmx-exporter\",delayedOperation=\"Produce\"}",
       "legendFormat": "{{delayedOperation}}:{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Zookeeper",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "panels": [
    {
     "title": "Alive connections",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "zookeeper_numaliveconnections{job=~\"zookeeper-jmx-exporter\"}",
       "legendFormat": "{{instance}}: {{replicaId}} [{{memberType}}]"
      }
     ]
    },
    {
     "title": "Request Latency - Max x Min x Avg ",
     "type": "graph",
     "description": "1-The amount of time it takes for the server to respond to a client request.\n2-The amount of time it takes for the server to respond to a client request.\n3-The amount of time it takes for the server to respond to a client request.",
     "gridPos": { "h": 18, "w": 16, "x": 8, "y": 5 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(zookeeper_maxrequestlatency[5m])",
       "legendFormat": "Max - {{ instance }}"
      },
      {
       "expr": "rate(zookeeper_minrequestlatency[5m])",
       "legendFormat": "Min -  {{ instance }}"
      },
      {
       "expr": "rate(zookeeper_avgrequestlatency[5m])",
       "legendFormat": "Avg - {{ instance }}"
      }
     ]
    },
    {
     "title": "Quorum size",
     "type": "stat",
     "description": "Minimum number of servers required to run the Zookeeper",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "count(zookeeper_quorumsize)" }
     ]
    },
    {
     "title": "Alive Connections",
     "type": "stat",
     "description": "The total count of client connections.",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(zookeeper_numaliveconnections)"
      }
     ]
    },
    {
     "title": "Watchers",
     "type": "stat",
     "description": "Number of watchers over Zookeeper znodes.\t",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(zookeeper_inmemorydatatree_watchcount)"
      }
     ]
    },
    {
     "title": "Znodes",
     "type": "stat",
     "description": "The number of znodes in the ZooKeeper namespace (the data).",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(zookeeper_inmemorydatatree_nodecount)"
      }
     ]
    },
    {
     "title": "Queued requests",
     "type": "graph",
     "description": "The number of queued requests when the server is under load and is receiving more sustained requests than it can process.",
     "gridPos": { "h": 9, "w": 16, "x": 8, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "zookeeper_outstandingrequests", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Zookeeper Status",
     "type": "bargauge",
     "description": "Zookeeper Server Status",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "up{job=\"zookeeper-jmx-exporter\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Packets Sent / sec",
     "type": "graph",
     "description": "The number of packets sent.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "pps", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "rate (zookeeper_packetssent{job=~\"zookeeper-jmx-exporter\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Packets Received / sec",
     "type": "graph",
     "description": "The number of packets received.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "pps", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "rate (zookeeper_packetsreceived{job=~\"zookeeper-jmx-exporter\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Latencia zookeeper (ms)",
     "type": "graph",
     "description": "The latency for ZooKeeper requests from the broker, in milliseconds.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_server_zookeeperclientmetrics_zookeeperrequestlatencyms{quantile=\"0.99\",job=~\"kafka-jmx-exporter\"}",
       "legendFormat": "{{instance}} 99%"
      },
      {
       "expr": "kafka_server_zookeeperclientmetrics_zookeeperrequestlatencyms{quantile=\"0.95\",job=~\"kafka-jmx-exporter\"}",
       "legendFormat": "{{instance}} 95%"
      }
     ]
    },
    {
     "title": "Time spent in GC",
     "type": "graph",
     "description": "Using rate(jvm_gc_collection_seconds_sum[5m]) you can see what proportion of time each type of GC is taking up",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "percent", "label": "% time in GC" }
     ],
     "targets": [
      {
       "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"zookeeper-jmx-exporter\"}[5m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "JVM Non Heap Memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "bytes", "label": "Memory" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_bytes_used{area=\"nonheap\", job=\"zookeeper-jmx-exporter\"}",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "JVM Heap Memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "bytes", "label": "Memory" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_bytes_used{area=\"heap\", job=\"zookeeper-jmx-exporter\"}",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "description": "% cpu utilization for server:",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "short", "label": "Cores" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=\"zookeeper-jmx-exporter\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka Connect",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Connectors",
     "type": "singlestat",
     "description": "The total number of task startups that this worker has attempted.",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 20 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "expr": "kafka_connect_worker_total" }
     ]
    },
    {
     "title": "Kafka Connect Status",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 7, "x": 3, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "up{job=\"kafka-connect-jmx-exporter\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "description": "% cpu utilization for server:",
     "gridPos": { "h": 8, "w": 14, "x": 10, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Cores" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=\"kafka-connect-jmx-exporter\"}[1m])",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Producer Connections",
     "type": "singlestat",
     "description": "The current number of active connections from producer.",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 26 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count (rate(kafka_producer_connection_count{job=\"kafka-connect-jmx-exporter\"}[1m]))"
      }
     ]
    },
    {
     "title": "Connector task state",
     "type": "graph",
     "description": "Connector status",
     "gridPos": { "h": 8, "w": 7, "x": 3, "y": 26 },
     "yaxes": [
      { "format": "short", "label": "Conn" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_connect_worker_connector_running_task_count{job=~\"kafka-connect-jmx-exporter\"})",
       "legendFormat": "running"
      },
      {
       "expr": "sum(kafka_connect_worker_connector_paused_task_count{job=~\"kafka-connect-jmx-exporter\"})",
       "legendFormat": "paused"
      },
      {
       "expr": "sum(kafka_connect_worker_connector_failed_task_count{job=~\"kafka-connect-jmx-exporter\"})",
       "legendFormat": "failed"
      },
      {
       "expr": "sum(kafka_connect_worker_connector_destroyed_task_count{job=~\"kafka-connect-jmx-exporter\"})",
       "legendFormat": "destroyed"
      },
      {
       "expr": "sum(kafka_connect_worker_connector_unassigned_task_count{job=~\"kafka-connect-jmx-exporter\"})",
       "legendFormat": "unassigned"
      }
     ]
    },
    {
     "title": "Time spent in GC",
     "type": "graph",
     "description": "Using rate(jvm_gc_collection_seconds_sum[5m]) you can see what proportion of time each type of GC is taking up",
     "gridPos": { "h": 7, "w": 7, "x": 10, "y": 28 },
     "yaxes": [
      { "format": "percent", "label": "% time in GC" }
     ],
     "targets": [
      {
       "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"kafka-connect-jmx-exporter\"}[1m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "JVM Memory",
     "type": "graph",
     "description": "Total of the heap and non-heap memory used by JVM",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 28 },
     "yaxes": [
      { "format": "bytes", "label": "Memory" }
     ],
     "targets": [
      {
       "expr": "sum without(area)(jvm_memory_bytes_used{job=\"kafka-connect-jmx-exporter\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Consumer Connections",
     "type": "singlestat",
     "description": "The current number of active connections from consumers.",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 31 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count (rate(kafka_consumer_connection_count{job=\"kafka-connect-jmx-exporter\"}[1m]))"
      }
     ]
    },
    {
     "title": "Producers vs Consumers",
     "type": "graph",
     "description": "Current number of active connections  from Consumers and Producers",
     "gridPos": { "h": 7, "w": 7, "x": 3, "y": 34 },
     "yaxes": [
      { "format": "short", "label": "Conn" }
     ],
     "targets": [
      {
       "expr": "count (rate(kafka_consumer_connection_count{job=\"kafka-connect-jmx-exporter\"}[1m]))",
       "legendFormat": "Consumers"
      },
      {
       "expr": "count (rate(kafka_producer_connection_count{job=\"kafka-connect-jmx-exporter\"}[1m]))\n",
       "legendFormat": "Producers"
      }
     ]
    },
    {
     "title": "Incoming bytes",
     "type": "graph",
     "description": "The average number of responses received per second for a node",
     "gridPos": { "h": 6, "w": 7, "x": 10, "y": 35 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_consumer_incoming_byte_total{job=\"kafka-connect-jmx-exporter\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Outgoing bytes",
     "type": "graph",
     "description": "The average number of outgoing bytes sent per second for a node.",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 35 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_consumer_outgoing_byte_total{job=\"kafka-connect-jmx-exporter\"})",
       "legendFormat": "{{clientId}}"
      }
     ]
    },
    {
     "title": "Number of Tasks",
     "type": "singlestat",
     "description": "Number of tasks that have run in the worker",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 36 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "kafka_connect_worker_task_count"
      }
     ]
    }
   ]
  }
 ]
}